services:
  ai-search-server:
    image: harbor.cloud.weique360.com/common/ai-search:amd64-v1.0.0
    platform: linux/amd64
    container_name: ai-search-server
    environment:
      - TZ=Asia/Shanghai
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8180:8000"
    networks:
      - app-network
    volumes:
      - ./server:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ["bash", 'start.sh']

  web-ui:
    image: harbor.cloud.weique360.com/common/nginx:amd64-v1.0.0
    platform: linux/amd64
    container_name: web-ui
    ports:
      - "8181:80"
    volumes:
      - ./front/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge